site_name: episteme
site_url: https://episteme-association.github.io

repo_url: https://github.com/episteme-association/documentation
repo_name: episteme-association/documentation

edit_uri: edit/main/docs/

nav:
  - Association Episteme:
    - index.md 
  - About Us:
    - about-us/index.md
  - Services:
    - services/index.md
    - Health Intelligence Partnership Project Coordination: services/hipp/index.md
    - Health Intelligence Network Governance: services/governance/index.md
    - Solution Design: services/solution-design/index.md
    - Health Intelligence: services/health-intelligence/index.md
  - Solutions:
    - Solutions/index.md
    - Public Health:
      - Solutions/Public-Health/index.md
      - Human Intelligence: Solutions/Public-Health/Human-Intelligence/index.md
      - Open Source Intelligence: Solutions/Public-Health/Open-Source-Intelligence/index.md
      - Early Warning and Alerting: Solutions/Public-Health/Early-Warning-and-Alerting/index.md
      - Integrated Disease Surveillance: Solutions/Public-Health/Integrated-Disease-Surveillance/index.md
      - Health Information Exchange: Solutions/Public-Health/Health-Information-Exchange/index.md
      - Pandemic Simulator: Solutions/Public-Health/Pandemic-Simulator/index.md
    - Healthcare:
      - Solutions/Healthcare/index.md
      - Self-observation:
        - Solutions/Healthcare/Self-observation/index.md
        - Personal Seizure Diary: Solutions/Healthcare/Self-observation/Personal-seizure-diary/index.md
        - Personal Glucose Monitor: Solutions/Healthcare/Self-observation/Personal-glucose-monitor/index.md
      - Clinical Decision Support: Solutions/Healthcare/Clinical-Decision-Support/index.md
  - Health Intelligence Network:
    - Health-Intelligence-Network/index.md
    - Health Intelligence Partnership Project: Health-Intelligence-Network/Partnership-Project/index.md
    - Health Intelligence Network Governance: Health-Intelligence-Network/Governance/index.md
    - Health Intelligence Services: Health-Intelligence-Network/Health-Intelligence-Services/index.md
  - Continuous Innovations:
    - Continuous-Innovations/index.md
    - Knowledge Models: Continuous-Innovations/Knowledge-Models/index.md
    - Web of Data Components: Continuous-Innovations/Web-of-Data-Components/index.md
    - Health Intelligence Network Search Engine: Continuous-Innovations/Web-of-Data-Search-Engine/index.md
    - Advanced Analytics Operationalisation: Continuous-Innovations/Advanced-Analytics-Operationalisation/index.md
  - Knowledge Base:
    - Knowledge-Base/index.md
    - Health Emergencies: Knowledge-Base/Health-Emergencies/index.md
    - Health Intelligence:
      - Knowledge-Base/Health-Intelligence/index.md
      - Surveillance: Knowledge-Base/Health-Intelligence/Surveillance/index.md
      - Contextual Analysis: Knowledge-Base/Health-Intelligence/Contextual-Analysis/index.md
      - Assessment: Knowledge-Base/Health-Intelligence/Threats-and-Opportunities-Assessment/index.md
      - Actionable Intelligence: Knowledge-Base/Health-Intelligence/Actionable-Intelligence/index.md

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
#    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
#    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
#    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/episteme-logo.png
  favicon: assets/favicon.png
  icon:
    repo: material/github

markdown_extensions:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
#  - material.extensions.preview:
#      configurations:
#        - sources: 
#            include:
#              - ...
#            exclude:
#              - ...
#        - targets: 
#            include:
#              - ...
#            exclude:
#              - ...

extra:
  alternate:
    - name: English
      link: ./en/ 
      lang: en
  generator: true

plugins:
  - search:
      enabled: true
      lang: en
  - meta:
      enabled: true
  - tags:
      enabled: true
      tags: true
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_hierarchy: true
      listings: true
      listings_toc: true
      shadow: true
      shadow_on_serve: true
      export: true

copyright: "<a rel=\"license\" href=\"https://episteme-association.github.io/documentation/\">Association Episteme's documentation</a> &copy; 2025 by Association Episteme is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">Creative Commons Attribution-ShareAlike 4.0 International<img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1\" alt=\"\"></a>"

