site_name: episteme
site_url: https://episteme-association.github.io/documentation

repo_url: https://github.com/episteme-association/documentation
repo_name: episteme-association/documentation

edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
#    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
#    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
#    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/episteme-logo.png
  favicon: assets/favicon.png
  icon:
    repo: material/github

markdown_extensions:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
#  - material.extensions.preview:
#      configurations:
#        - sources: 
#            include:
#              - ...
#            exclude:
#              - ...
#        - targets: 
#            include:
#              - ...
#            exclude:
#              - ...

extra:
  alternate:
    - name: English
      link: ./en/ 
      lang: en
  generator: true

plugins:
  - search:
      enabled: true
      lang: en
  - meta:
      enabled: true
  - tags:
      enabled: true
      tags: true
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_hierarchy: true
      listings: true
      listings_toc: true
      shadow: true
      shadow_on_serve: true
      export: true

copyright: "<a rel=\"license\" href=\"https://episteme-association.github.io/documentation/\">Association Episteme's documentation</a> &copy; 2025 by Association Episteme is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">Creative Commons Attribution-ShareAlike 4.0 International<img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1\" alt=\"\"></a>"

